Numpy

In [4]:
#array = list 
import numpy as np

py_list = [1,2,3,4,5,6,7,8,9]
# numpy arry
np_array = np.array([1,2,3,4,5,6,7,8,9])
print(type(np_array))
print(type(py_list))

py_multi = [[1,2,3],[4,5,6],[7,8,9]]
np_multi = np_array.reshape(3,3)

print(py_multi)
print(np_multi)
print(np_array.ndim)
print(np_multi.ndim) # ndim metodu arrayin kaç boyutlu olduğunu gösterir.

print(np_array.shape)
print(np_multi.shape) #shape metodu kaça kaçlık bir array  olduğunu belirtir.

<class 'numpy.ndarray'>
<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
(9,)
(3, 3)


Numpy dizileri ile çalışma

In [6]:
import numpy as np

# result = np.array([1,3,5,7,9])
# result = np.arange(1,10) #nparange() elemanları belirttiğimiz aralıkta sıralar.
# result = np.arange(10,100,3)
# result = np.zeros(10) # zeros() 0 lardan oluşan bir dizi oluşturur.
# result = np.ones(10) #sadece 1lerden oluşan dizi oluşturur.
# result = np.linspace(0,100,5) # 0dan başlar 100e kadar 5 e böler bölünenleri yazdırır.
# result = np.linspace(0,5,5) # 0dan başlar 100e kadar 5 e böler bölünenleri yazdırır.
# result = np.random.randint(0,10) # random rastgele bir sayı üretir.,
# result = np.random.randint(20)
# result = np.random.randint(1,10,3) # 1 ile 10 arasında rastgele 3 sayı üretir.
# result = np.random.rand(5) # 0 ile 1 arasında 5 sayı üretir.
# result = np.random.randn(5) # - değerleri de içinde kullanır.
# np.array = np.arange(50)
# np.multi = np.array.reshape(5,10) #5 satır 10 sütündan oluşan matris oluşturur.
# print(np.multi.sum(axis = 1)) #satırların toplamı print(np.multi.sum(axis = 1)) #satırların toplamı 
# print(np.multi.sum(axis = 0)) #sütünların toplamı 

rnd_numbers = np.random.randint(1,100,10)
print(rnd_numbers)
# result = rnd_numbers.max()
# result = rnd_numbers.min()
result = rnd_numbers.mean()
result = rnd_numbers.argmax() # maximum olan sayının index numarasını verir.
result = rnd_numbers.argmin()

print(result) 

[17 96 70 99 35  4 98 83 73 75]
5


Numpy Dizilerinin indekslenmesi

In [27]:
import numpy as np

numbers = np.array([0,5,10,20,25,50,75])

result = numbers[5]
result = numbers[-1]
result = numbers[0:3]
result = numbers[:3]
result = numbers[3:]
result = numbers[::]# bütün listeyi getirir.
result = numbers[::-1] # bütün listeyi tersten getirir.

numbers2 = np.array([[0,5,10],[20,25,50],[70,85,95]])
result = numbers2[0]
result = numbers2[2]
result = numbers2[0,2] # 0. indeksteki satırın 2. indeksteki elemanını getirir.
result = numbers2[:,2]# bütün satırların 2. indeksteki elemanını getirir.
result = numbers2[:,0:2]# bütün satırların 0 ile 2  indeks arasındaki elemanları getirir.

result = numbers2[-1,:]
result = numbers2[0,:]
result = numbers2[:2,:2]

# print(result)

arr1 = np.arange(0,10)
# arr2 = arr1 #referans kopyalaması
arr2 = arr1.copy() #kopyalar ama farklı bir adreste tanımlanır. referans tipli olmaz.


arr2[0] = 20

print(arr1)
print(arr2)



[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]


Numpy dizi operasyonları

In [64]:
import numpy as np


numbers1 = np.random.randint(10,100,6)
numbers2 = np.random.randint(10,100,6)
print(numbers1)
print(numbers2)

result = numbers1 + numbers2 # aynı indeksteki elemanları toplar bir dizi içerisine atar.
result = numbers1 + 10
result = numbers1 - numbers2
result = numbers1 * numbers2

result = np.sin(numbers) # sinüsü alır ve yeni bir dizi içerisinde gösterir.
result = np.sqrt(numbers1)
result = np.log(numbers1)

mNumbers1 = numbers1.reshape(2,3)
mNumbers2 = numbers2.reshape(2,3)

result = np.vstack((mNumbers1,mNumbers2))# dikey 
print(result)
result = np.hstack((mNumbers1,mNumbers2))#yatay olarak ekleme işlemi yapar.
#stack işlemi iki matrisi dikey veya yatay olarak birleştirme işlemi yapar.
print(result)


result = numbers1 >= 50 #numbers1 deki elemanların hepsine bakar bool değer döndürür.
#koşul sağlanmıyorsa false döndürür.
result = numbers1 % 2 == 0
print(result)

print(numbers1[result]) # kooşulu sağlayan elemanları bir dizi içerisinde döndürür.

print(mNumbers1)
# print(mNumbers2)


[13 75 80 57 61 41]
[69 96 17 74 15 76]
[[13 75 80]
 [57 61 41]
 [69 96 17]
 [74 15 76]]
[[13 75 80 69 96 17]
 [57 61 41 74 15 76]]
[False False  True False False False]
[80]
[[13 75 80]
 [57 61 41]]


Numpy (Uygulama)

In [55]:
import numpy as np

# result = np.array([10,15,30,45,60])
# result = np.arange(5,15)
# result = np.arange(50,100,5)
# result = np.zeros(10)
# result = np.ones(10)
# result = np.linspace(0,100,5)
# result = np.random.randint(10,30,5)
# result = np.random.randn()
# result = np.random.randint(10,50,15).reshape(3,5)
matris = np.random.randint(-50,50,15).reshape(3,5)
# print(matris)
# # rowTotal = matris.sum(axis = 1) #sütün 
# # colTotal = matris.sum(axis = 0) #satır daki sayıların toplamını verir.
# # print(rowTotal)
# # print(colTotal)

# result = matris.max()
# result = matris.min()
# result = matris.mean()
# result = matris.argmax()
# result = matris.argmin()
# print(result)

print(matris)
arr = np.arange(10,20)
result = arr[:3]
result = arr[::-1]
result = matris[0]
result = matris[2,3]
result = matris[:,0]
# result = matris ** 2
ciftler = matris[matris % 2 == 0] # bu şekilde olduğunda elemanların kendisi gelir.
result = ciftler > 0 #bu şekilde olduğunda true false bilgisi döndürür dizi içinde
print(ciftler[ciftler > 0])
print(result)

[[-35 -12 -16  38   0]
 [-30  14  -7  21 -37]
 [-22 -45  49  34 -21]]
[38 14 34]
[False False  True False False  True False  True]
